pipeline {

    agent any

    stages {

        // ejercicio 2.1
        stage('Info') {
            steps {
                echo "2.1 Info"
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
                echo "Branch: ${env.BRANCH_NAME}"
            }
        }
        // ejercicio 2.2 + 2.3
        stage('CI - Lint') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'make lint'
            }
        }

        stage('CI - Test') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                echo "2.2 Unit test"
                sh 'mvn test'
            }
        }
        // final del bloque de stages
    }
}