// FUNCIONES
def runInDocker(String image, Closure body) {
    docker.image(image).inside { body() }
}

// PIPELINE
pipeline {

    agent any

    stages {

        stage('Info') {
            steps {
                echo "2.1 Info"
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
                echo "Branch: ${env.BRANCH_NAME}"
            }
        }

        stage('CI - Build tools image') {
            steps {
                script {
                    docker.build(env.CI_IMAGE_NAME, "-f devops/ci.Dockerfile .")
                }
            }
        }

        stage('CI - Lint') {
            script {
                devopsLib.runInDocker(env.CI_IMAGE_NAME) {
                    sh 'make lint'
                }
            }
        }

        stage('CI - Test') {
            steps {
                script {
                    devopsLib.runInDocker(env.CI_IMAGE_NAME) {
                        sh 'mvn test'
                        sh 'make test'
                    }
                }
            }
        }
        // final del bloque de stages
    }
}